# Generated by Django 3.2.25 on 2026-09-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0025_terms_accepted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="admin_notes",
            field=models.TextField(blank=True, default="", max_length=10000),
        ),
    ]
