"""Pure accessors for Stripe webhook/API payloads.

Deliberately free of Django models and DB access so `api_admin_tools` can
import these without creating a cycle back through `api_billing.views`.
"""


def invoice_subscription_id(invoice_data):
    # Stripe API 2025-03-31.basil moved Invoice.subscription to
    # Invoice.parent.subscription_details.subscription. Pick whichever the
    # payload actually exposes so a webhook endpoint signed with either API
    # version works. The `in details` check (rather than truthiness) means an
    # explicit `null` in the new schema is honored as "no subscription on this
    # invoice" instead of silently falling back to the legacy field.
    parent = invoice_data.get("parent") or {}
    details = parent.get("subscription_details") or {}
    if "subscription" in details:
        return details["subscription"]
    return invoice_data.get("subscription")


def invoice_billing_reason(invoice_data):
    return invoice_data.get("billing_reason")


def is_subscription_invoice(invoice_data):
    """True when Stripe says this invoice was generated by a subscription.

    Covers subscription_create / subscription_cycle / subscription_update /
    subscription_threshold, and excludes one-off charges ("manual").
    """
    return (invoice_billing_reason(invoice_data) or "").startswith("subscription")
